spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true # JPA로 생성되는 쿼리 확인
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console # h2 db 웹 클라이언트 접속 url
  devtools:
    livereload:
      enabled: true # 정적파일들의 실시간 갱신
  freemarker:
    cache: false
#security:
#  basic:
#    enabled: false # security 기본 인증 옵션 제거
#logging:
#  level:
#    org.hibernate.type: trace  # JPA로 생성되는 쿼리의 파라미터 값 확인